version: '3.1'

volumes:
  esdata:
  pgdata:
  pglog:
  nginxlog:


networks:
  gn-network:
    driver: bridge


services:
  www:
    image: nginx
    ports:
      - 80:80
    environment:
      - NGINX_PUBLIC_HOST=$FQDN
    volumes:
      - ./nginx_local:/etc/nginx/templates
      - ./nginx_html:/usr/share/nginx/html
      - nginxlog:/var/log/nginx
    depends_on:
      - geonetwork
      - geoserver
    networks:
      - gn-network
    restart: always

  database:
    image: postgis/postgis:11-2.5
    environment:
      POSTGRES_USER: geonetwork
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_DB: geonetwork
    command: [ "postgres",
               "-c", "log_statement=all",
               "-c", "logging_collector=true",
               "-c", "log_file_mode=0644",
               "-c", "log_directory=/var/log/postgresql",
               "-c", "log_filename=postgresql.log" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql
      - ./volumes/backups/database:/apps/backups/database
    networks:
      - gn-network


  geonetwork:
    image: pigeosolutions/sib-geonetwork:latest
    restart: always
    environment:
      DATA_DIR: /catalog
      ENABLE_CAS: "no"
      ENABLE_FLAT_FORM: "yes"
      ADMIN_USERS: "jean.pommier@pi-geosolutions.fr thomas.milon@mnhn.fr"
      GEONETWORK_URL: "${HTTP_SCHEME}://${FQDN}/geonetwork"

      JAVA_OPTS: >
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx1G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalog/data/resources
        -Dgeonetwork.data.dir=/catalog/data/metadata_data
        -Dgeonetwork.config.dir=/catalog/config
        -Dgeonetwork.codeList.dir=/catalog/config/codelist
        -Dgeonetwork.backup.dir=/catalog/data/backup
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins

      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200

      KB_URL: http://kibana:5601

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: database
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: geonetwork
      GEONETWORK_DB_USERNAME: geonetwork
      GEONETWORK_DB_PASSWORD: geonetwork
      NF_MENU_URL: "http://localhost/NFpage.html"
    volumes:
      - ./volumes/geonetwork_data:/catalog
    depends_on:
      - elasticsearch
      - database
    networks:
      - gn-network

  geoserver:
    image: pigeosolutions/geoserver:latest
    environment:
      GEOSERVER_CSRF_WHITELIST: ${FQDN}
#      PROXY_BASE_URL: ${HTTP_SCHEME}://${FQDN}/geoserver
    volumes:
      - ./volumes/geoserver_datadir:/mnt/geoserver_datadir
      - ./volumes/geoserver_geodata:/mnt/geoserver_geodata
      - ./volumes/geoserver_tiles:/mnt/geoserver_tiles
    restart: unless-stopped
    networks:
      - gn-network

  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - gn-network

  kibana:
    image: kibana:7.9.2
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /geonetwork/dashboards
      SERVER_REWRITEBASEPATH: 'false'
      KIBANA_INDEX: .dashboards
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
    networks:
      - gn-network
